import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core"
import { Provider } from "./AppProvider"
import '@mantine/core/styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}

export const fetchCache = 'default-no-store'
export const dynamic = 'force-dynamic'
